# Name of the docker compose "project"
name: disqube-example

# Service definition
services:
  qube:
    image: disqube-test
    command: tail -f /dev/null
    networks:
      - qubenet
    volumes:
      - ../test/pcap:/usr/disqube/pcap
      - ../bin:/usr/disqube/bin2
    ports:
      - "1234:1234"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

# Definition of custom networks
networks:
  qubenet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.10.0/24
          gateway: 172.30.10.254
